apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-deployment-app
      version: blue
  template:
    metadata:
      labels:
        app: blue-green-deployment-app
        version: blue
    spec:
      containers:
      - name: app
        image: aniketk1827/blue-green-deployment:blue
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Test@123
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
