apiVersion: apps/v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: blue-green-deployment-app
    version: green